Flutter tutorial post editorial review
ably/docs pull request #1010
Opened 2021-01-12 15:38 UTC by Srushtika

2021-01-18 11:39 UTC, fliptopbox commented
@Srushtika if this is ready please assign it to someone, and also add your own approval.

2021-01-18 11:52 UTC, Srushtika commented
@fliptopbox looks like I can't be my own approver, so added you.

2021-01-18 13:06 UTC, fliptopbox approved these changes

2021-01-19 10:48 UTC, fliptopbox requested changes

2021-01-19 10:48 UTC, fliptopbox commented on content/tutorials/flutter-cryptocurrency-app.textile
> +```[flutter]
please change the language to `dart` for all instances (there are about 4-5)

2021-01-19 11:54 UTC, tbedford commented
I will do a more detailed review later. But for now will just add comments. Flutter icon appears missing:

![image](https://user-images.githubusercontent.com/25511700/105031288-0357cf00-5a4d-11eb-838f-b5eb39510863.png)

2021-01-19 11:55 UTC, tbedford commented
Formatting not quite right on directory structure diagram:

![image](https://user-images.githubusercontent.com/25511700/105031417-34380400-5a4d-11eb-9910-d76bd8153b74.png)

2021-01-19 11:57 UTC, tbedford commented
Code snippets not quite right here:

![image](https://user-images.githubusercontent.com/25511700/105031638-7e20ea00-5a4d-11eb-9b74-264bdac0461c.png)

2021-01-19 12:06 UTC, Srushtika commented
Thanks for the comments @tbedford, I hadn't checked the preview on the website yet. I'll push some fixes. @fliptopbox as for the Flutter icon on the tutorials page, do you want me to raise a ticket for this?

2021-01-19 12:37 UTC, fliptopbox commented
@Srushtika Nah, don't create a ticket, I will grab the SVG asset from this ...
https://commons.wikimedia.org/wiki/File:Dart-logo-wordmark.svg
and make a greyscale version.

2021-01-19 13:43 UTC, fliptopbox commented
@Srushtika @tbedford the icons belong to the website assets, here is the PR that adds `ai-dart` and `ai-flutter` SVG icons that are used in the tutorial filter widget.

NOTE!!!!! you will need to update the languge list, so that it has the icon reference

2021-01-19 15:18 UTC, tbedford approved these changes
I've not run through the tutorial step by step, but have reviewed website rendering locally. The issues I raised have been fixed, and looks good.

2021-01-19 15:26 UTC, fliptopbox approved these changes

2021-01-19 15:29 UTC, merged