Fix Channel Enumeration tutorial
ably/docs pull request #1111
Opened 2021-06-11 11:07 UTC by marklewin

The tutorial was broken and the live demo used Basic auth (see: [DOC-321](https://ably.atlassian.net/browse/DOC-321)). Also used the opportunity to rewrite for better clarity and replace an out of date screenshot.

2021-06-15 19:03 UTC, m-hulbert requested changes
Reads well to me! My only suggestion would be to replace the instances of "we" and "our" in the text. There's also one incorrect link to fix.

2021-06-16 08:56 UTC, marklewin commented on content/tutorials/channel-enumeration-rest.textile
> +For simplicity, this tutorial will use "basic authentication":/core-features/authentication#basic-authentication. In production, "Ably advises that you use token authentication":http://localhost:4000
Good spot!

2021-06-16 08:57 UTC, marklewin commented
> Reads well to me! My only suggestion would be to replace the instances of "we" and "our" in the text. There's also one incorrect link to fix.

Couldn't find any "we" ... fixed a couple of "our"

2021-06-18 13:12 UTC, tbedford approved these changes
Checked under website and nanoc. Looks good. Also made sure live demo was working.

2021-06-21 11:37 UTC, m-hulbert commented
> > Reads well to me! My only suggestion would be to replace the instances of "we" and "our" in the text. There's also one incorrect link to fix.
> 
> Couldn't find any "we" ... fixed a couple of "our"

There's just the one in `We provide a REST client library to make it straightforward to access the REST API...` and it's all good from me.

2021-06-21 12:26 UTC, m-hulbert approved these changes

2021-06-22 11:05 UTC, merged