Add a PR template
ably/docs pull request #1129
Opened 2021-07-06 15:54 UTC by tbedford

> NOTE: To reviewers - please do not review PRs in the DRAFT state, as the PR may change substantially before ready to review. Thanks.                                                                                                       
                                                                                                                       
## Description                                                                                                         
                                                                                                                       
A PR description indicating the purpose of the PR.                                                                     
                                                                                                                       
* [JIRA ticket](link).                                                                                                 
                                                                                                                       
## Review                                                                                                              
                                                                                                                       
Instructions on how to review the PR.                                                                                  
                                                                                                                       
* [Page to review](link)

2021-07-07 16:42 UTC, marklewin requested changes
I'm just wondering if we can make the NOTE a bit harder to ignore by using **bold**, etc?

2021-07-07 16:42 UTC, marklewin commented on pull_request_template.md
> +> NOTE: To reviewers - please do not review PRs in the DRAFT state, as the PR may change substantially before ready to review. Thanks.
```suggestion
> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.
```

2021-07-08 09:46 UTC, marklewin approved these changes
LGTM!

2021-07-08 10:11 UTC, m-hulbert approved these changes
LGTM 👍

2021-07-08 10:21 UTC, merged