Add all 3 callbacks for activation lifecycle (2 were missing) & update to latest ably-cocoa API
ably/docs pull request #1177
Opened 2021-08-20 12:14 UTC by ben-xD

There are 3 callback events for push devices: activate, deactivate and update failed. 2 were missing.

In the objective-C and Swift code blocks, I also set the delegate manually, because this is the non-legacy API, as per the internal code of Ably-cocoa (not documented anywhere 😂). The automatic delegate has the variable name `legacyDelegate`.

2021-08-20 12:59 UTC, ben-xD commented
To see the preview, visit https://ably-docs-pr-1177.herokuapp.com/general/push/activate-subscribe/ and go to the `Handle push notification lifecycle`.

2021-08-23 09:28 UTC, marklewin requested changes
Some suggestions re: formatting

2021-08-23 09:28 UTC, marklewin commented on content/general/push/activate-subscribe.textile
> +There are three events which correspond to the three <span lang="android">intent broadcasts you should listen to.</span><span lang="objc,swift">delegate methods you should implement.</span>:
```suggestion
There are three events which correspond to the three <span lang="android">broadcast intents you should listen to</span><span lang="objc,swift">delegate methods you should implement</span>:
```

2021-08-23 09:28 UTC, marklewin commented on content/general/push/activate-subscribe.textile
> + - Push activation completion (succeeds/ fails): <span lang="android">Listen for the @io.ably.broadcast.PUSH_ACTIVATE@ action in a broadcast intent</span><span lang="objc">Implement @- (void)didActiv
```suggestion
- Push activation completion:= (Success or failure). <span lang="android">Listen for the @io.ably.broadcast.PUSH_ACTIVATE@ action in a broadcast intent</span><span lang="objc">Implement @- (void)didActivateAblyPush:(nullable ARTErrorInfo *)error;@</span><span lang="swift">@func didActivateAblyPush(_ error: ARTErrorInfo?)@</span>. Once the device has successfully been activated, you can subscribe to push notifications on channels to receive push notifications from Ably.
```

2021-08-23 09:28 UTC, marklewin commented on content/general/push/activate-subscribe.textile
> + - Push deactivation completion (suceeds/ fails): <span lang="android">Listen for the @io.ably.broadcast.PUSH_DEACTIVATE@ action in a broadcast intent</span><span lang="objc">Implement @- (void)didDe
```suggestion
- Push deactivation completion:= (Success or failure). <span lang="android">Listen for the @io.ably.broadcast.PUSH_DEACTIVATE@ action in a broadcast intent</span><span lang="objc">Implement @- (void)didDeactivateAblyPush:(nullable ARTErrorInfo *)error@</span><span lang="swift">@func didDeactivateAblyPush(_ error: ARTErrorInfo?)@</span>
```

2021-08-23 09:28 UTC, marklewin commented on content/general/push/activate-subscribe.textile
> + - Push update completion (fails only): <span lang="android">Listen for the @io.ably.broadcast.PUSH_UPDATE_FAILED@ action in a broadcast intent</span><span lang="objc">Implement @- (void)didAblyPushR
```suggestion
- Push update completion:= (Failure only). <span lang="android">Listen for the @io.ably.broadcast.PUSH_UPDATE_FAILED@ action in a broadcast intent</span><span lang="objc">Implement @- (void)didAblyPushRegistrationFail:(nullable ARTErrorInfo *)error;@</span><span lang="swift">@func didAblyPushRegistrationFail(_ error: ARTErrorInfo?)@</span>
```

2021-08-23 09:28 UTC, marklewin commented on content/general/push/activate-subscribe.textile
> +An example to listen to the push activation event is as follows:
```suggestion
The following example demonstrates how to listen to the push activation event:
```

2021-08-23 09:28 UTC, marklewin commented on content/general/push/activate-subscribe.textile
> + - Push update completion (fails only): <span lang="android">Listen for the @io.ably.broadcast.PUSH_UPDATE_FAILED@ action in a broadcast intent</span><span lang="objc">Implement @- (void)didAblyPushR
**Note**: The preceding three suggested changes show the events in a tabular format, which IMO makes them a little easier to read: 
![image](https://user-images.githubusercontent.com/18176755/130424225-050d7058-66b0-4751-93ff-92b5705b116a.png)

2021-08-23 19:35 UTC, ben-xD commented
Thanks @marklewin , I've committed all your suggestions as they make sense.

2021-09-07 08:55 UTC, marklewin approved these changes
LGTM

2021-09-07 10:07 UTC, merged