DOC-570: Document channel mode flags
ably/docs pull request #1301
Opened 2022-02-17 11:03 UTC by m-hulbert

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

This PR documents channel mode flags in the realtime channels page and also updates the best practice guide for being present without subscribing.

## Review

To review this PR, see:

* [Realtime channels]()
* [Best practice guide]()

2022-02-17 12:26 UTC, Sapples reviewed
One question about the table headers, LGTM otherwise.

2022-02-17 12:26 UTC, Sapples commented on content/realtime/channels.textile
> +| Flag | Description |
Should the headers be bold?

2022-02-17 12:32 UTC, tbedford requested changes
Do we need to say anything about how channel mode flags relate to capabilities?

Table format may not be quite right:

![image](https://user-images.githubusercontent.com/25511700/154481471-2e87cf71-61c6-44b3-9050-e7cd859ab7df.png)

I think we need to specify Flag and Description as headings in the Textile markup.

2022-02-18 17:57 UTC, m-hulbert commented on content/realtime/channels.textile
> +| Flag | Description |
Yes it should! Good spot :-)

2022-02-21 11:23 UTC, merged