Create Ably Kafka Connector tutorial
ably/docs pull request #1343
Opened 2022-04-05 11:03 UTC by tomczoink

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

This is a basic tutorial demonstrating a simple usage of the Kafka Ably Connector. It largely duplicates the instructions from the Connector's README, with some additional context to help users get started.

* [Jira ticket](https://ably.atlassian.net/browse/DOC-297?atlOrigin=eyJpIjoiY2MzMzEwY2NiOWViNGNmZmFjZWYyNmJhMDg4NGY2NmIiLCJwIjoiaiJ9).

## Review

Ensure contents of the tutorial renders correctly, and is accurate and informative enough to get started.

* [Page to review](link)

2022-04-07 10:06 UTC, tomczoink commented
@ikbalkaya a few things from me on this:

* I've used just a simple topic-to-channel mapping in this, but I imagine if the topic to many channel implementation may be better to demonstrate. Is that already implemented in the current main branch, and if so what is needed to make that work?
* Are there any particular features of the Connector you think are worth mentioning/demonstrating which haven't been yet?

2022-04-07 11:17 UTC, ikbalkaya requested changes
Generally looks good to me, I made some suggestions and a small request for a configuration. 

One of the things I think we could improve is that current instructions on producing messages and subscribing to them is a bit restrictive as it only uses Kafka console producer. I wonder whether it would be worth to write something on producing messages from a Kafka producer app - and subscribing them using a client library (might be out of scope of this document)

2022-04-07 11:17 UTC, ikbalkaya commented on content/tutorials/ably-kafka-connector.textile
> +connector.class = com.ably.kafka.connect.ChannelSinkConnector
This is currently required but honestly I think this should already be embedded as default connector. I will see if I can make it optional and then we might remove this from the instructions.

2022-04-07 11:17 UTC, ikbalkaya commented on content/tutorials/ably-kafka-connector.textile
> +client.id = kafka-connect-ably-example
`channel` also should be here :)

2022-04-07 11:24 UTC, ikbalkaya commented
> @ikbalkaya a few things from me on this:
> 
> * I've used just a simple topic-to-channel mapping in this, but I imagine if the topic to many channel implementation may be better to demonstrate. Is that already implemented in the current main branch, and if so what is needed to make that work?
> * Are there any particular features of the Connector you think are worth mentioning/demonstrating which haven't been yet?

@tomczoink 
* Topic to many channel should work. This is explained https://github.com/ably/kafka-connect-ably#dynamic-channel-configuration
* It might be worth to mention the lots of configuration properties we support and ones that we enable interpolation (channel name and message name) and how this is bringing routing flexibility for users.

2022-04-07 13:28 UTC, tomczoink commented
>I wonder whether it would be worth to write something on producing messages from a Kafka producer app - and subscribing them using a client library (might be out of scope of this document)
I definitely think it'd be great for us to produce a more fleshed out blog post at some point demonstrating a more realistic setup with a kafka producer app, clients producing data going into Kafka via the Kafka Rule and processed data returning to clients via the Connector. 


> Topic to many channel should work. This is explained https://github.com/ably/kafka-connect-ably#dynamic-channel-configuration
>  It might be worth to mention the lots of configuration properties we support and ones that we enable interpolation (channel name and message name) and how this is bringing routing flexibility for users.

Great thanks! I'll add in details on dynamic channel configuring and try to include more of an overview of the configuration properties + link to the README in the connector repo for more details.

2022-04-07 17:22 UTC, ikbalkaya commented on content/tutorials/ably-kafka-connector.textile
> +connector.class = com.ably.kafka.connect.ChannelSinkConnector
This one doesn't look possible so I think this can be left as it is

2022-04-07 17:24 UTC, ikbalkaya commented on content/tutorials/ably-kafka-connector.textile
> +In the above code when producing data, we're specifying how we'll include a key in the messages via the proprties @key.separator@ and @parse.key@. The separator is defined to be a colon (:), so the m
```suggestion
In the above code when producing data, we're specifying how we'll include a key in the messages via the properties @key.separator@ and @parse.key@. The separator is defined to be a colon (:), so the messages both have a key of @my_group@.
```

2022-04-19 08:59 UTC, tomczoink commented
@ikbalkaya are you happy with the tutorial now in its current state?

2022-04-19 09:27 UTC, tomczoink commented
Good spot, thanks @ikbalkaya ! If the rest looks good please do approve and I'll merge it in 😄.

2022-04-19 09:28 UTC, ikbalkaya approved these changes
Looks good to me 👍

2022-04-19 09:28 UTC, merged