Remove RSC20 from client lib feature spec
ably/docs pull request #1401
Opened 2022-04-21 16:38 UTC by owenpearson

Resolves #1381.

An alternative approach could be to label this section as deprecated but I decided that since the functionality has already been removed from all SDKs it's unlikely to provide any value keeping it.

2022-04-21 19:30 UTC, lmars approved these changes

2022-04-22 07:35 UTC, tbedford approved these changes

2022-04-22 12:42 UTC, QuintinWillison requested changes
Yay 🎉  - though we had agreed previously that we wouldn't delete the clauses entirely, as there's a risk someone might add a new clause using that old number, hence the need to replace clause textual contents with "This clause has been deleted." per [our guidelines](https://github.com/ably/engineering/blob/main/sdk/features-specification.md#guidelines).

2022-05-09 14:06 UTC, owenpearson commented
@QuintinWillison Good point, I've changed it now to just add "(deprecated)" to each bit instead of removing. This convention is already used elsewhere in the spec (see TS12d for example).

2022-05-10 09:42 UTC, QuintinWillison approved these changes

2022-05-10 10:05 UTC, merged