Added kafka auth mechanisms
ably/docs pull request #1414
Opened 2022-05-03 13:27 UTC by Sapples

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

A PR description indicating the purpose of the PR.

* [Jira epic ticket](link) - if applicable.
* [Jira ticket](link).

## Review

Instructions on how to review the PR. 

* [Page to review](link)

2022-05-03 13:41 UTC, tbedford requested changes

2022-05-03 13:41 UTC, tbedford commented on content/general/firehose/kafka-rule.textile
> +* "SASL/SCRAM-SHA-257":https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_scram.html#kafka-sasl-auth-scram
> SASL/SCRAM-SHA-257

Typo. Should be 256.

2022-05-03 16:02 UTC, tbedford requested changes

2022-05-03 16:02 UTC, tbedford commented on content/general/firehose/kafka-rule.textile
> +The supported Authentication Mechanisms are are:
> The supported Authentication Mechanisms are are: 
 
Sorry, missed this before double "are".

2022-05-03 16:31 UTC, Sapples commented on content/general/firehose/kafka-rule.textile
> +The supported Authentication Mechanisms are are:
Good spot, thanks!

2022-05-04 08:15 UTC, tbedford approved these changes

2022-05-04 08:24 UTC, merged