[EDX-142] Add an overview to integrations
ably/docs pull request #1435
Opened 2022-05-23 10:08 UTC by m-hulbert

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

This PR adds an overview page to the integrations section.

See [JIRA](https://ably.atlassian.net/browse/EDX-142) for further information. 

## Review

View the new integrations overview to review this PR.

2022-05-23 14:58 UTC, Sapples approved these changes
One comment that is down to personal preference/taste, otherwise LGTM.

2022-05-24 09:22 UTC, Srushtika requested changes
Thanks, @m-hulbert - I've added a few comments but would be good to jump on a 10min call to discuss further. It would be good to align the content in this page with the IA plan

2022-05-24 09:22 UTC, Srushtika commented on content/general/integrations.textile
> +Integrations enable data to be sent from Ably to external services and for external services to send data to Ably channels.
Maybe add the word 'channels' for both directions?

2022-05-24 09:22 UTC, Srushtika commented on content/general/integrations.textile
> +Ably events can be used to trigger webhook requests to external services such as "IFTTT":https://ifttt.com/ and "Zapier":https://zapier.com/ or invoke functions such as "Amazon Lambda functions":http
Think we can skip the 'functions' in Amazon Lambda

2022-05-24 09:22 UTC, Srushtika commented on content/general/integrations.textile
> +Ably events can be used to trigger webhook requests to external services such as "IFTTT":https://ifttt.com/ and "Zapier":https://zapier.com/ or invoke functions such as "Amazon Lambda functions":http
It's confusing to see 'events' when the rest of the documentation talks in terms of 'messages'. Could you add some context so readers can understand what we mean by 'events' here?

2022-05-24 09:22 UTC, Srushtika commented on content/general/integrations.textile
> +h2(#webhooks). Events via webhooks
It'll be useful to provide some context around events vs continuous streaming before getting into each section

2022-05-24 09:22 UTC, Srushtika commented on content/general/integrations.textile
> +Data can be sent from an external service into Ably channels. Configure an "incoming webhook":#incoming-webhooks in Ably to use in an external service, or use the "Ably Kafka Connector":/ to stream d
It feels like we have inbound and outbound integrations mixed up leading to confusion

2022-06-13 10:21 UTC, Srushtika approved these changes
Looks good to me, thanks @m-hulbert . @tbedford are you able to have a look at this and merge it in while Mark is away?

2022-06-13 10:26 UTC, merged