[EDU-771] Render the DEMO cards in the tutorials page
ably/docs pull request #1447
Opened 2022-06-08 07:54 UTC by fliptopbox

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

A PR description indicating the purpose of the PR.

* [Jira epic ticket](link) - if applicable.
* [Jira ticket](link).

## Review

Instructions on how to review the PR. 

* [Page to review](link)

2022-06-13 16:18 UTC, fliptopbox commented
hi @tbedford not sure who to ask for a PR review for the update DEMO files.

2022-06-14 08:05 UTC, tbedford commented
@fliptopbox - I won't have time to look at this any time soon I'm afraid. I'm sure @marklewin and @leggetter are familiar with this and could test locally etc. Let me know if that's not going to be possible, and I will try and shuffle things around. Thanks.

2022-06-14 09:11 UTC, marklewin requested changes
Some of the card text doesn't read well, or even fit in the cards. I've suggested some alternative text for the excerpts.

Also, I note from the [demo app](https://website-edu-771-add-dem-n3gg3p.herokuapp.com/tutorials) that clicking on the card doesn't do anything, whereas the UI suggests that it should? Maybe it should link to the GH repo and then perhaps you could just have "Live demo" as a link at the bottom of each card?

2022-06-14 09:11 UTC, marklewin commented on content/tutorials/demo-realtime-midi-player.textile
> +excerpt: A realtime midi keyboard in the browser. Uses WebAPIs and pubsub to create a virtual jam session.
```suggestion
excerpt: A realtime MIDI keyboard in the browser. Uses Web APIs and pub/sub to create a virtual jam session.
```

2022-06-14 09:11 UTC, marklewin commented on content/tutorials/demo-realtime-midi-player.textile
> +meta_description: A realtime midi keyboard in the browser. Uses WebAPIs and pubsub to create a virtual jam session.
```suggestion
meta_description: A realtime MIDI keyboard in the browser. Uses Web APIs and pub/sub to create a virtual jam session.
```

2022-06-14 09:11 UTC, marklewin commented on content/tutorials/demo-realtime-multiplayer-space-invaders.textile
> +The game is built using PhaserJS."
```suggestion
meta_description: A realtime multiplayer Space Invaders game built with Ably and the Phaser 3 game framework. The game runs in the browser and its state is managed by a central NodeJS server.
```

2022-06-14 09:11 UTC, marklewin commented on content/tutorials/demo-realtime-multiplayer-space-invaders.textile
> +The game is built using PhaserJS."
```suggestion
excerpt: A realtime multiplayer Space Invaders game built with Ably and the Phaser 3 game framework. The game runs in the browser and its state is managed by a central NodeJS server.
```

2022-06-14 12:12 UTC, fliptopbox commented
@marklewin please review. thanks

2022-06-14 13:16 UTC, marklewin reviewed
@fliptopbox I can't see if the new text fits the cards, because the build seems to have failed? The text changes look good however, although I note that the meta_description in the Google Sheet doesn't match what we're now using here.

2022-06-14 13:35 UTC, fliptopbox commented
@marklewin 

1. i have added a new `excert` column to track the differences in the [google sheet](https://docs.google.com/spreadsheets/d/1M1Tenb02zZKsVTma6WpSQ3SfW0poIzp9UDo8KnsBPUE/edit?usp=sharing) with respective word count - i will need to update the repos as part of Git gardening sessions.
2. You can see the [docs preview app here](https://ably-docs-add-demo-card-mpja6b.herokuapp.com/), the UI changes **will not** be reflected on the website UI (that the preview app is for Website and uses SHA from the previous commit)

2022-06-14 13:43 UTC, marklewin approved these changes
Not able to preview, but text LGTM! 👍

2022-06-14 13:52 UTC, marklewin approved these changes
Re-approving, because @fliptopbox still unable to merge.

2022-06-14 14:28 UTC, merged