DRAFT: [EDX-129] New design for site top nav
ably/docs pull request #1514
Opened 2022-08-02 08:57 UTC by MymmiJ

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

This is to get the docs site top nav looking like this Figma representation: https://www.figma.com/file/vyr9ZPZ15eUWtCKSEktdEL/API-refs?node-id=414%3A8643

* [Jira ticket](https://ably.atlassian.net/browse/EDX-129).

## Review

Instructions on how to review the PR. 

* [Page to review](http://localhost:8000/docs/api/realtime-sdk) - any page should work, check the top nav and ensure it looks as expected.
* If you can run the website with `bin/dev` (it only really depends on postgresql and redis + rake jobs), you can test logging in and viewing your account details in that dropdown menu.

2022-08-03 09:53 UTC, DuncanEdwards requested changes
Before I even start on the code there are probably layout issues to resolve:
![image](https://user-images.githubusercontent.com/960045/182579618-e597e877-2db3-4b89-ad6d-d5a5577d6f2c.png)

Also, is the LHS column going to be a fixed width? In the design the search is right next to the logo, but in the implementation that LHS column can grow, taking the Search box away from the logo. Is that OK? Would Lenka be happy with that?

2022-08-03 10:03 UTC, MymmiJ commented
I wasn't sure what to do when the page spaces out more, I think it looks better the way you propose - I can cluster the search + docs to the left and everything else to the right.

2022-08-03 11:12 UTC, MymmiJ commented
> Before I even start on the code there are probably layout issues to resolve: ...
> 
> Also, is the LHS column going to be a fixed width? In the design the search is right next to the logo, but in the implementation that LHS column can grow, taking the Search box away from the logo. Is that OK? Would Lenka be happy with that?

I've made these changes, the logo & search button/dropdown menu items now cluster together.

2022-08-05 14:34 UTC, DuncanEdwards reviewed
Seem to be missing top and bottom delimiter lines:
![image](https://user-images.githubusercontent.com/960045/183098954-c3526994-2f2f-4b5d-be44-aeccf8b546d1.png)

Whereas on the website meganav it looks different:
![image](https://user-images.githubusercontent.com/960045/183099247-5a1c1bfb-f25e-4edb-bc63-b5eda0064846.png)

2022-08-09 16:43 UTC, MymmiJ commented
> Seem to be missing top and bottom delimiter lines: ![image](https://user-images.githubusercontent.com/960045/183098954-c3526994-2f2f-4b5d-be44-aeccf8b546d1.png)
> 
> Whereas on the website meganav it looks different: ![image](https://user-images.githubusercontent.com/960045/183099247-5a1c1bfb-f25e-4edb-bc63-b5eda0064846.png)

I've had a go at changing these to look more like the website meganav.

2022-08-10 10:04 UTC, DuncanEdwards requested changes
Minor things + break out `index.ts`

2022-08-10 10:04 UTC, DuncanEdwards commented on src/components/Header/TopMainNav/index.tsx
> +  const menuItems: (keyof typeof dropdownData)[] = ['API References', 'Resources'];
index!!

2022-08-10 14:31 UTC, DuncanEdwards approved these changes

2022-08-10 14:37 UTC, merged