Edx 124 generate random channel names
ably/docs pull request #1522
Opened 2022-08-05 09:39 UTC by MymmiJ

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

Replaces {{RANDOM_CHANNEL_NAME}} tokens with a random channel name; memoized so it's the same per page loaded.

Also some small refactors to the Code.js block.

* [Jira ticket](https://ably.atlassian.net/browse/EDX-124).

## Review

Instructions on how to review the PR. 

Visit pages, you should see a random channel name each time you reload the page e.g.:

```
var realtime = new Ably.Realtime({
  key: '*********************************************************',
  clientId: 'bob' }
);
var channel = realtime.channels.get('can-guy-pea');
channel.presence.subscribe('enter', function(member) {
  alert('Member ' + member.clientId + ' entered');
});
channel.presence.enter();
```

The API Key text will vary based on whether the app has access to an API key or not. You can fake an API key with:

* GATSBY_DOCS_SIGNED_IN - set to any string to force the application to behave as though you are logged in
* GATSBY_DOCS_API_KEYS - set to any string to force the application to behave as though you have API keys available

When you press the 'Copy' button under these conditions, you should see (for example):

```
var realtime = new Ably.Realtime({
  key: 'dev_api_key',
  clientId: 'bob' }
);
var channel = realtime.channels.get('can-guy-pea');
channel.presence.subscribe('enter', function(member) {
  alert('Member ' + member.clientId + ' entered');
});
channel.presence.enter();
```

* [Page to review](http://localhost:8000/docs/realtime/presence)

2022-08-05 14:27 UTC, DuncanEdwards requested changes
I was expected stars here?
![image](https://user-images.githubusercontent.com/960045/183097824-a9e9bb69-3786-4a0b-a6b0-b23bc2c5a5a1.png)
instead of `loaidng API key`?

Other than that only minor refactors.

2022-08-05 14:27 UTC, DuncanEdwards commented on src/components/blocks/software/Code/index.js
> +            '*********************************************************',
`Array(n).join("*")`

2022-08-05 14:27 UTC, DuncanEdwards commented on src/components/blocks/software/Code/MultilineCodeContent.tsx
> +  const contentMaybeWithKey = dataContainsKey
Refactor into a method and maybe the first one could be an non linline if statement. Multiple nested inlines are a bit much and hurt my head!

2022-08-05 16:29 UTC, MymmiJ commented
> *

Hmm if you set those env variables then it's possibly because of how you run the app, I've noticed that npm runs its own terminal session so doesn't always have access to your env variables

2022-08-08 09:17 UTC, DuncanEdwards requested changes
Sorry! Looks good but one more TINY change

2022-08-08 09:17 UTC, DuncanEdwards commented on src/components/blocks/software/Code/index.js
> +        ? contentWithRandomChannelName.replace(/{{API_KEY}}/g, new Array(57).join('*'))
Sorry, last one, that 57 needs to be a constant. Seems like an arbitrary number, so good luck naming that!

2022-08-08 09:27 UTC, DuncanEdwards approved these changes

2022-08-08 11:22 UTC, merged