implement aws feedback
ably/docs pull request #1553
Opened 2022-08-23 07:19 UTC by Sapples

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

A PR description indicating the purpose of the PR.

* [Jira epic ticket](link) - if applicable.
* [Jira ticket](link).

## Review

Instructions on how to review the PR. 

* [Page to review](link)

2022-08-23 12:16 UTC, lmars commented on content/tutorials/aws-persistence.textile
> +In this tutorial you will learn how to create a channel rule that intercepts messages sent to a channel and persists them to a file in "AWS Simple Storage Service (S3)":https://aws.amazon.com/s3/. No
We should recommend the use of an AWS Kinesis rule for when batching is required, and then have Kinesis write to S3:

https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-s3

2022-08-24 09:09 UTC, tbedford requested changes

2022-08-24 09:09 UTC, tbedford commented on content/tutorials/aws-persistence.textile
> +In this tutorial you will learn how to create a channel rule that intercepts messages sent to a channel and persists them to a file in "AWS Simple Storage Service (S3)":https://aws.amazon.com/s3/. No
> https://ably.com/docs/general/firehose/kinesis-rule

https://ably.com/docs not required. Also I would add a short sentence somewhere in this section pointing people at our Kinesis tutorial, that would be a very useful starting point for someone who wants to implement this.

2022-08-24 09:09 UTC, tbedford commented on content/tutorials/aws-persistence.textile
> +The solution code for this tutorial is "available on Github":https://github.com/ably/tutorials/tree/aws-persistence.
This is good. Can we also add a "Download source code for this tutorial" link as the first item in the "Next steps" section too, as we only have the one link to the source code.

2022-08-24 14:52 UTC, tbedford approved these changes

2022-08-30 08:11 UTC, lmars approved these changes

2022-08-30 08:12 UTC, merged