[EDU-1053] - correct rendering
ably/docs pull request #1635
Opened 2022-10-19 14:46 UTC by Sapples

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

Rendering error with the table correction. Changed the formatting to show correctly then added example for clarification, example in code tags as it contained an @ symbol.

* [Bugs](https://ably.atlassian.net/browse/EDU-608).
* [Token revocation rendering error](https://ably.atlassian.net/browse/EDU-1053).

## Review

Check the rendering of the table for token revocation:

* [Auth and security](https://ably-docs-edu-1053-toke-4tj5lf.herokuapp.com/core-features/authentication/#token-revocation)

2022-10-20 08:23 UTC, tbedford requested changes

2022-10-20 08:23 UTC, tbedford commented on content/core-features/authentication.textile
> +- clientId := For a string @clientId@, matches tokens that have a non-empty @clientId@ equal to that given, for example: <code>targets: ["clientId:client1@example.com" ]</code>
I think we need something before the table to explain the format for target specifiers, so by the time the developer gets into the table they know the format would be along the lines of `clientId: <some_string>`, etc.

I also think we could clarify the description here a bit. For example, `clientId` is the key, not the value. We need to make that crystal clear. The example would then provide extra clarification as to what's going on.

2022-10-20 08:23 UTC, tbedford commented on content/core-features/authentication.textile
> +- resourceName := For a @resourceName@ that exactly matches one of the "resource names":/core-features/authentication#wildcards present in the token capabilities. Note that this is not the same thing
This change looks slightly odd compared to what you did in the previous section. The key is `channel` and the value is a resource name. We need to make that clearer. I think the description needs to be clarified.

2022-10-20 08:23 UTC, tbedford commented on content/core-features/authentication.textile
> +- revocationKey := Matches tokens that have a @revocationKey@ claim that matches the given @revocationKey@, for example: <code>targets: ["revocationKey:users.group1@example.com"]</code>
Again there is some confusion around what is the key and what is the value in the description I think. We need to clarify this.

2022-10-25 14:24 UTC, tbedford requested changes

2022-10-25 14:24 UTC, tbedford commented on content/core-features/authentication.textile
> +- clientId := Key that takes a string value, matches tokens that have a non-empty @clientId@ equal to that given, for example: <code>targets: ["clientId:client1@example.com" ]</code>
> clientId := Key that takes a string value, matches tokens

Doesn't quite read right to me. Perhaps something like:

This target specifier will match tokens that have the specified @clientId@. For example, `targets: ["clientId:client1@example.com" ]` matches tokens containing the `clientId` of `client1@example.com`.

2022-10-25 14:24 UTC, tbedford commented on content/core-features/authentication.textile
> +- revocationKey := Key that takes a string value, matches tokens that have a @revocationKey@ claim that matches the given @revocationKey@, for example: <code>targets: ["revocationKey:users.group1@exa
> Key that takes a string value, matches tokens that have a @revocationKey@ claim that matches the given @revocationKey@,

A little confusing. Perhaps reword along similar lines to the previous suggestion.

2022-10-25 15:55 UTC, tbedford commented
@MarkMon-Ably - are you looking at the raw source, or a rendered output?

2022-10-25 16:07 UTC, tbedford commented
@Sapples - the deployment wasn't there, so I've built it and updated the link to the review up in the PR description. 

@MarkMon-Ably - we usually set up our PR descriptions to contain a link to a review app:

![image](https://user-images.githubusercontent.com/25511700/197825164-48344157-a9df-4f55-ab3f-77b15266e12f.png)

If you click that link, you should be able to see the rendered output.

2022-10-25 17:10 UTC, MarkMon-Ably commented
Ah, okay. The whitespace I was seeing is the gaps for images. Good to know.

2022-10-26 11:24 UTC, MarkMon-Ably approved these changes

2022-11-16 12:23 UTC, tbedford approved these changes

2022-11-16 12:23 UTC, merged