[EDX-261] - Footer for Docs pages only
ably/docs pull request #1673
Opened 2022-10-28 16:10 UTC by aralovelace

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

A PR description indicating the purpose of the PR.

* [Jira epic ticket](link) - if applicable.
* [Jira ticket](link).

## Review

Instructions on how to review the PR. 

* [Page to review](link)

2022-11-01 11:49 UTC, MymmiJ requested changes
Can you fix the rebase issue by copy-pasting textile files from main please?

2022-11-01 11:51 UTC, MymmiJ commented on src/components/Footer/Footer.tsx
> +        <div className="max-w-screen-xl mx-auto py-64 ui-grid-gap grid ui-grid-px grid-cols-6">
This can be its own component

2022-11-01 11:51 UTC, MymmiJ commented on src/components/Footer/Footer.tsx
> +            <div className="pt-16 flex items-center">
This can be its own component

2022-11-01 11:52 UTC, MymmiJ commented on src/components/Footer/Footer.tsx
> +          {menuDataItems
This can be its own component

2022-11-01 11:56 UTC, MymmiJ commented on src/components/Footer/FooterLogoAndStatus.tsx
> +export const FooterLogoAndStatus = () => (
This is an odd combination of things; is there a reason these two are tied together?
If not, I would suggest making FooterStatus its own component and just rendering <Logo> and <FooterStatus> alongside each other
If there is a good reason, you should use that reason as the name of this component

2022-11-01 11:57 UTC, MymmiJ commented on src/components/Footer/FooterMenu.tsx
> +              <li className="p-menu-row-snug pb-8" key={item.label}>
This can be its own component

2022-11-01 11:57 UTC, MymmiJ commented on src/components/Footer/Footer.tsx
> +        <div className="max-w-screen-xl mx-auto py-40 border-t border-mid-grey w-full">
This can be its own component

2022-11-01 11:57 UTC, MymmiJ commented on src/components/Footer/Footer.tsx
> +                  <a key={link.label} className="ui-footer-link" href={link.link}>
This can be its own component

2022-11-01 11:59 UTC, MymmiJ commented on src/components/Footer/Footer.tsx
> +  const bottomLinks = data.bottomMenu.items;
if you do `data.bottomMenu.items ?? [];` for all of these, I think you won't have to check inline to see if the items exist before mapping later?

2022-11-01 14:36 UTC, aralovelace commented
@MymmiJ  updated and convert it into smaller components

2022-11-01 17:07 UTC, aralovelace commented on src/components/Footer/Footer.tsx
> +      <footer className="bg-white antialiased" data-id="footer">
@MymmiJ  just updated

2022-11-02 17:25 UTC, MymmiJ approved these changes
Approved, if there are more design changes to make from Srushtika please do make them but the code is good.

2022-11-02 18:06 UTC, merged