Edx 461
ably/docs pull request #1708
Opened 2022-11-07 14:01 UTC by aralovelace

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

A PR description indicating the purpose of the PR.

* [Jira epic ticket](link) - if applicable.
* [Jira ticket](link).

## Review

Instructions on how to review the PR. 

* [Page to review](link)

2022-11-07 17:28 UTC, Srushtika requested changes
Hey @aralovelace, just noticed that this gets super messy for SSE API and REST API pages as it shows the routes instead of methods and properties. Is it possible to skip those two pages from this logic? cc: @MymmiJ 

- https://ably-docs-next-staging.herokuapp.com/docs/api/rest-api
- https://ably-docs-next-staging.herokuapp.com/docs/api/sse?lang=python

2022-11-08 09:41 UTC, aralovelace commented
> Hey @aralovelace, just noticed that this gets super messy for SSE API and REST API pages as it shows the routes instead of methods and properties. Is it possible to skip those two pages from this logic? cc: @MymmiJ
> 
> * https://ably-docs-next-staging.herokuapp.com/docs/api/rest-api
> * https://ably-docs-next-staging.herokuapp.com/docs/api/sse?lang=python

@MymmiJ  hmmm how can we differentiate the use of H6 per page? aside from getting adding a condition to to check if the sitename is not [/api/rest-api](https://ably-docs-next-staging.herokuapp.com/docs/api/rest-api) and [api/sse?lang=python](https://ably-docs-next-staging.herokuapp.com/docs/api/sse?lang=python) ? and I know this would be a messy process

2022-11-08 14:38 UTC, aralovelace commented
@Srushtika  @MymmiJ  this is updated now

2022-11-08 15:05 UTC, snikidev commented on data/createPages/createContentMenuDataFromPage.js
> +        }
this seems exactly the same 🤔 or am I missing something?

2022-11-08 15:07 UTC, snikidev commented on data/createPages/createContentMenuDataFromPage.js
> +      let newID = id;
i think we can simplify it to 
```
const newId = id ?? idFromName(menuItemName)
```

2022-11-08 15:11 UTC, snikidev commented on data/createPages/createContentMenuDataFromPage.js
> +        }
ahhhh I get it now. Well, we can also do this
```
page.attribs = {
  ...(page.attribs || {}),
  id: idFromName(menuItemName)
}
```

2022-11-08 16:08 UTC, snikidev approved these changes
Love it! 🔥

2022-11-08 16:18 UTC, MymmiJ commented on data/createPages/createContentMenuDataFromPage.js
> +    const isRestFUL = httpRESTfulMethods.some((method) => name.toUpperCase().startsWith(method));
Shouldn't this just be `name`? I don't think we want anything starting with `get` to be treated the same as `GET`, it's not really REST associated in the same reliable way

2022-11-09 11:02 UTC, MymmiJ approved these changes

2022-11-09 11:33 UTC, merged