[EDX-413] - basics - what
ably/docs pull request #1866
Opened 2023-03-16 09:13 UTC by Sapples

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

Add a page giving an overview of the basics of Ably.

* [Jira ticket](https://ably.atlassian.net/browse/EDX-413).

## Review

Check /basics/ably in the new toolchain.

2023-05-19 17:54 UTC, tbuntel requested changes
@m-hulbert I have a large number of comments. Might it be better to work on this in a google doc?

2023-05-19 17:54 UTC, tbuntel commented on content/basics/ably.textile
> +Ably’s realtime platform provides a scalable, fault-tolerant and worldwide publish/subscribe(pub/sub) network. Providing SDKs in a variety of programming languages with both REST and realtime interfa
This should align with our core messaging. 
"Ably is the platform to power synchronized digital experiences in realtime. Ably's SDKs and APIs power realtime capabilities like Chat, Data Broadcast, Data Synchronization, Multiplayer Collaboration, and Notifications."

2023-05-19 17:54 UTC, tbuntel commented on content/basics/ably.textile
> +* Live Chat - chat for customer support or community engagement
"chat for customer support, live events, or community engagement"

2023-05-19 17:54 UTC, tbuntel commented on content/basics/ably.textile
> +Ably uses the pub/sub architectural pattern to enable any number of publishers to publish data and any number of subscribers to subscribe to that data. This works with Ably's "concept of channels":/c
Would it be good to give an example here? something like "pub/sub could be used to power live data feeds such as sports scores, travel updates, stocks, currency or auction prices."

2023-05-19 17:54 UTC, tbuntel commented on content/basics/ably.textile
> +Ably’s "presence":/presence-occupancy/presence feature enables clients or devices to announce their presence on a channel. Other devices or services may then subscribe to these presence events, such
Again, an example here could be "Presence could be used to power a live avatar stack to show what users are present in a virtual space (e.g. whiteboard, document, or worksheet)"

2023-05-19 17:54 UTC, tbuntel commented on content/basics/ably.textile
> +Ably's "Push Notifications":/push feature enables messages to be pushed to subscribers without needing a device to maintain a connection to Ably.
"enables messages to be pushed to subscribers on mobile devices without needing to maintain a connection to Ably.

2023-05-19 17:54 UTC, tbuntel commented on content/basics/ably.textile
> +The "realtime interface":/basics/use-ably#realtime-interface establishes and maintains a constant connection to Ably, enabling realtime messages to be sent both to and from Ably. Using multiplexed "W
Incomplete sentence. S/b "Using multiplexed "WebSocket":/https://ably.com/topic/websockets connections enables multiple channels to share a single connection without having to fall back to inefficient techniques like HTTP polling.

2023-05-19 17:54 UTC, tbuntel commented on content/basics/ably.textile
> +Ably has a Global Network of 7 geographically-distributed core routing datacenters and 307 edge acceleration points-of-presence(PoPs). Ably's Global Network ensures unrivalled realtime messaging, dat
385 edge acceleration points-of-presence (per https://ably.com/network)

2023-05-23 13:54 UTC, m-hulbert commented
Old PR - closing in favour of a new one.

2023-05-23 13:54 UTC, closed without merging