[WEB-3286] Increase top to prevent unwanted scrolling
ably/docs pull request #2043
Opened 2023-10-24 17:58 UTC by kephail

## Description

Right sidebar was scrolling up, being obscured by top nav. Increased top to accomodate this

* [Jira ticket](https://ably.atlassian.net/browse/WEB-3286) 

## Review

view any page where the language selector appears on in the right nav on docs eg: `/docs/getting-started/setup`

2023-10-25 13:56 UTC, m-hulbert approved these changes
Fixes the cut-off 👍

2023-10-31 14:44 UTC, kennethkalmer requested changes
Thanks @kephail, this looks great. Can I ask that you undo the order changes in the `import` statements please? We've had issues with the CSS modules in the past when the order changed due to your fancy development setup :) I'm all for removing unused vars though, thanks for keeping it clean!

2023-11-01 12:51 UTC, kennethkalmer commented
@kephail can you rebase and squash all the commits into one please? then it will be good to go! 🎉

2023-11-01 16:55 UTC, kennethkalmer approved these changes

2023-11-01 16:55 UTC, merged