[WEB-3917] - Link whole card
ably/docs pull request #2253
Opened 2024-08-29 15:50 UTC by aralovelace

…text

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

A PR description indicating the purpose of the PR.

* [Jira epic ticket](link) - if applicable.
* [Jira ticket](link).

## Review

Instructions on how to review the PR. 

* [Page to review](link)

2024-08-29 16:34 UTC, jamiehenson requested changes
Works well from what I can see in the testing pages, I just have a few comments when it comes to component and data structures. Nice cleanups around tags and returning null though 👍

2024-08-29 16:34 UTC, jamiehenson commented on data/yaml/page-content/asset-tracking.yaml
> +        link: '/asset-tracking/using-the-sdks'
Looking at all the usages of `link` here - it occurs to me that we probably don't need to add in a new field here, as `link` replicates `links[0].href`. 

We could cut the complexity of this a little bit by removing `link` and instead offering a helper that takes `links` as an argument and safely returns the first `href` from it. This helper should be put in a location that makes sense to be imported by all the components that use it (i.e. one level up from all of them).

2024-08-29 16:34 UTC, jamiehenson commented on src/components/Homepage/BodySection/Card/FeatureCard.tsx
> +  <a href={link} className="pointer flex justify-between flex-col">
It's worth being mindful here of `validateDOMNesting` console errors that arise as a result of this ([reference](https://www.dhiwise.com/post/mastering-validatedomnesting-best-practices)). 

In short, it breaks the HTML standards if we put certain tags inside certain other tags (with `div`s, pretty much anything goes) - in this example, `a` tags from `<Links ... />` conflict with this outer `a` tag.

We should aim to reduce these to a minimum, so worth a look at restructuring this and testing the other pages here with this in mind.

2024-08-29 16:34 UTC, jamiehenson commented on src/components/Image.tsx
> +    return null;
Nice, we should always return `null` from components when not rendering content 👍

2024-08-29 16:34 UTC, jamiehenson commented on src/components/ProductPage/BodySection/Card/FeatureCard.tsx
> +  <a
Similar `validateDOMNesting` concern as the other comment

2024-08-30 10:54 UTC, aralovelace commented
thanks @jamiehenson  for your constructive feedback. They are now updated.

2024-08-30 13:41 UTC, jamiehenson approved these changes
Looks good, just remember to remove this before merging 👍 https://github.com/ably/docs/pull/2253/files#diff-bbe0b63a7d562937af3cc869d1be2ff929c38015592548ba94095a6ac6c6f4a8R27

2024-08-30 14:36 UTC, m-hulbert approved these changes
LGTM!

2024-08-30 15:32 UTC, merged