EDU-1650: Adds push lifecycle section and adds push lifecycle diagram
ably/docs pull request #2261
Opened 2024-09-03 17:21 UTC by franrob-projects

This PR:

- Adds a new push notification lifecycle section to the overview page.
- Adds the actual push notification lifecycle diagram.
- Adds an explanation of the push notification diagram.

[EDU-1650](https://ably.atlassian.net/browse/EDU-1650)

2024-10-01 16:32 UTC, owenpearson requested changes
looks fine overall, some nitpicks:

2024-10-01 16:32 UTC, owenpearson commented on content/push/index.textile
> +** Your server sends the notification data to Ably, a realtime messaging platform.
i think it reads a bit funny briefly explaining what ably is, anyone reading this should already be aware of this so i'd opt to omit this.

```suggestion
** Your server sends the notification data to Ably.
```

2024-10-01 16:32 UTC, owenpearson commented on content/push/index.textile
> +** Ably then forwards the packaged message to the appropriate push notification service _FCM, APNs, or Web Push_.
web push is not a push notification service, rather a specification which is implemented with different push services depending on the browser.
```suggestion
** Ably then forwards the packaged message to the appropriate push notification service _FCM_, _APNs_, or in the case of Web Push, the browser vendor's notification service.
```

2024-10-01 16:32 UTC, owenpearson commented on content/push/index.textile
> +** The selected push notification service _FCM, APNs, or Web Push_ takes responsibility for delivering the notification to the target devices.
see above regarding 'web push' as a push service

2024-10-01 16:32 UTC, owenpearson commented on content/push/index.textile
> +** The push notification finally arrives at the end-use's devices or browsers, displaying the notification on their screen.
```suggestion
** The push notification finally arrives at the end-user's devices or browsers, displaying the notification on their screen.
```

2024-10-10 09:02 UTC, franrob-projects commented
> looks fine overall, some nitpicks:

Hi @owenpearson thanks for the feedback. Please see: 65343c9be2096db9c8d2253e5529cd325b9e6c3b

2024-10-14 08:54 UTC, owenpearson approved these changes
LGTM

2024-10-16 08:04 UTC, m-hulbert reviewed
My only comment is that both the text and diagram assume that a publish originates from a server... it may be the case that a client publishes to a push-enabled channel.

2024-10-18 11:46 UTC, m-hulbert requested changes

2024-10-18 11:46 UTC, m-hulbert commented on content/push/index.textile
> +** The process begins with your app (client) or server, which publishes a push notification -- this could be any backend service that needs to send notifications to users' devices.
```suggestion
** The process begins with your app (client) or server, which publishes a push notification.
```

2024-10-18 11:46 UTC, m-hulbert commented on content/push/index.textile
> +** After receiving the push notification from your app or server, Ably processes and packages the notification with any additional data payload. This payload may include data such as message content,
```suggestion
** After receiving the push notification, Ably processes and packages the notification.
```

2024-10-18 11:46 UTC, m-hulbert commented on content/push/index.textile
> +** Ably then forwards the packaged message to the appropriate push notification service _FCM_, _APNs_, or in the case of Web Push, the browser vendor's notification service.
>browser vendor's notification service

Is this correct?

2024-10-18 11:46 UTC, m-hulbert commented on content/push/index.textile
> +** The push notification finally arrives at the end-user's devices or browsers, displaying the notification on their screen.
```suggestion
** The push notification arrives at the end-user's devices or browsers, displaying the notification on their screen.
```

2024-10-22 14:55 UTC, m-hulbert approved these changes

2024-10-22 14:59 UTC, merged