[EDU-1631] Spaces Component Locking example
ably/docs pull request #2290
Opened 2024-10-18 12:29 UTC by GregHolmes

This PR contains the two code samples for the new Examples section we are creating. It contains a Typescript and a React version for Component Locking with Spaces. Which will be rendered in the code sandbox live examples in the future, along with others.

The README within each directory /examples/spaces-component-locking/javascript and /examples/spaces-component-locking/react contains information on how to get these running.

[Jira epic ticket](https://ably.atlassian.net/browse/EDU-1541)
[Jira ticket](https://ably.atlassian.net/browse/EDU-1631).

2024-10-18 18:28 UTC, ttypic commented on examples/spaces-component-locking/react/src/hooks/useLiveValue.tsx
> +  console.log(channelName);
Do we need this `console.log`?

2024-10-18 18:28 UTC, ttypic approved these changes
LGTM

2024-11-08 16:53 UTC, m-hulbert requested changes
If you remove focus (e.g. click on your other window) then your component is cleared. This is different behaviour to the current example, and I think we need to keep it in order to display the functionality correctly. (JS)

The React example has the issue of reading its CSS from `public` still.

2024-11-08 16:53 UTC, m-hulbert commented on examples/spaces-component-locking/page.md
> +Manage concurrent access to shared resources within your collaborative application. This feature is particularly useful for preventing conflicts in collaborative environments, ensuring that only one
```suggestion
Manage concurrent access to shared resources within your application and prevent conflicts in collaborative environments, ensuring that only one user can modify a specific component at a time.
```

2024-11-08 16:53 UTC, m-hulbert commented on examples/spaces-component-locking/page.md
> +Users can lock components within a collaborative application.
```suggestion
Enable users to lock components for editing within a collaborative application.
```

2024-11-08 16:53 UTC, m-hulbert commented on examples/spaces-component-locking/page.md
> +* [`SpaceProvider`](https://ably.com/docs/spaces/react#spaces-provider): manages the state and functionality of a specific space, providing access to real-time interactions within that space via Reac
real-time --> realtime

2024-11-08 16:53 UTC, m-hulbert commented on examples/spaces-component-locking/page.md
> +Component locking are implemented using [Ably Spaces](https://ably.com/docs/products/spaces). The Spaces SDK contains a set of purpose-built APIs that abstract away the complexities involved in manag
```suggestion
Component locking is implemented using [Ably Spaces](https://ably.com/docs/products/spaces). The Spaces SDK contains a set of purpose-built APIs that abstract away the complexities involved in managing the state of components accessibility in a collaborative application. It is built on top of Ably's core platform, and so it provides the same performance and scaling guarantees.
```

2024-11-08 16:53 UTC, m-hulbert commented on examples/spaces-component-locking/page.md
> +Component locking enhances various collaborative applications, such as, in document editing tools, it can prevent simultaneous edits to the same section. In project management software, it can ensure
```suggestion
Component locking enhances applications where multiple users can edit the same fields, such as spreadsheets, slide shows and forms. It is a key component in maintaining data integrity and preventing conflicting changes.
```

2024-11-19 14:21 UTC, m-hulbert reviewed
This all works perfectly now. 

I think we need to add the `ChannelProvider` to the React entry and `publish()` to the JS one.

I also think it might be worth calling out the providers / methods that we're using from Pub/Sub separately (just a sentence rather than another section header). Thoughts?

2024-11-22 11:34 UTC, m-hulbert approved these changes

2024-11-22 13:45 UTC, merged