[EDU-1630] - Spaces Member Location example
ably/docs pull request #2291
Opened 2024-10-18 12:50 UTC by GregHolmes

This PR contains the two code samples for the new Examples section we are creating. It contains a Typescript and a React version for Component Locking with Spaces. Which will be rendered in the code sandbox live examples in the future, along with others.

The README within each directory /examples/spaces-member-location/javascript and /examples/spaces-member-location/react contains information on how to get these running.

[Jira epic ticket](https://ably.atlassian.net/browse/EDU-1541)
[Jira ticket](https://ably.atlassian.net/browse/EDU-1630).

2024-10-21 14:05 UTC, ttypic approved these changes
LGTM

2024-11-08 16:44 UTC, m-hulbert requested changes
Same minor issue as with avatars - I don't think we should be able to have the same colour or name appear for each user (only replicated in JS so far)

Then just a couple of minor copy changes 👍

2024-11-08 16:44 UTC, m-hulbert commented on examples/spaces-member-location/page.md
> +* [`SpaceProvider`](https://ably.com/docs/spaces/react#spaces-provider): manages the state and functionality of a specific space, providing access to real-time interactions within that space via Reac
real-time --> realtime

2024-11-08 16:44 UTC, m-hulbert commented on examples/spaces-member-location/page.md
> +Track the locations of other users in an application.
```suggestion
Track the location of other users within an application.
```

2024-11-08 16:44 UTC, m-hulbert commented on examples/spaces-member-location/page.md
> +Track and display the location of users within an application, such as a form field they have selected, the cell they're currently editing in a spreadsheet, or the slide they're viewing on a slide de
```suggestion
Track and display the location of users within an application, such as which form field they have selected, the cell they're currently editing in a spreadsheet, or the slide they're viewing on a slide deck.
```

2024-11-08 16:44 UTC, m-hulbert commented on examples/spaces-member-location/page.md
> +Member location are implemented using [Ably Spaces](https://ably.com/docs/products/spaces). The Spaces SDK contains a set of purpose-built APIs that abstract away the complexities involved in managin
```suggestion
Member locations are implemented using [Ably Spaces](https://ably.com/docs/products/spaces). The Spaces SDK contains a set of purpose-built APIs that abstract away the complexities involved in managing the locations of participants focus in a collaborative application. It is built on top of Ably's core platform, and so it provides the same performance and scaling guarantees.
```

2024-11-15 10:02 UTC, m-hulbert approved these changes
LGTM!

2024-11-15 13:36 UTC, merged