[EDU-1628] - Spaces Live Cursors example
ably/docs pull request #2292
Opened 2024-10-18 13:04 UTC by GregHolmes

This PR contains the two code samples for the new Examples section we are creating. It contains a Typescript and a React version for Live Cursors with Spaces. Which will be rendered in the code sandbox live examples in the future, along with others.

The README within each directory /examples/spaces-live-cursors/javascript and /examples/spaces-live-cursors/react contains information on how to get these running.

[Jira epic ticket](https://ably.atlassian.net/browse/EDU-1541)
[Jira ticket](https://ably.atlassian.net/browse/EDU-1628).

2024-10-21 16:23 UTC, ttypic reviewed
LGTM

2024-11-06 17:35 UTC, m-hulbert requested changes
The JavaScript example is only displaying cursors when you hover over the text.

2024-11-06 17:35 UTC, m-hulbert commented on examples/spaces-live-cursors/page.md
> +Live Cursors with Ably Spaces enables realtime tracking and display of user cursor positions within your application. This feature significantly enhances the collaborative experience by providing vis
Mixture of capitalisation for live cursors; it should be lower case throughout.

2024-11-06 17:35 UTC, m-hulbert commented on examples/spaces-live-cursors/page.md
> +# Live cursors for applications
The title doesn't follow the same format as the Chat ones. Maybe something like "Tracking users' cursors"?

2024-11-06 17:35 UTC, m-hulbert commented on examples/spaces-live-cursors/page.md
> +Enable members to see other member's cursors live in realtime within your application
```suggestion
Label and track the cursors of users in an application.
```

2024-11-06 17:35 UTC, m-hulbert commented on examples/spaces-live-cursors/page.md
> +Live Cursors can add value to various collaborative applications. In online whiteboarding tools, they allow team members to see where others are pointing or drawing. In collaborative coding environme
```suggestion
Track and display the position of users' cursors within an application to provide visual cues of other users' activities and areas of focus in shared workspaces.

Live cursors are utilized in applications such as online whiteboards to enable users to see where others are pointing or what they are drawing. They are also used in slideshow applications to enable users to see which slide each member is interacting with.
```

2024-11-06 17:35 UTC, m-hulbert commented on examples/spaces-live-cursors/page.md
> +Live cursors can be implemented using [Ably Spaces](https://ably.com/docs/products/spaces). The Spaces SDK contains a set of purpose-built APIs that abstract away the complexities involved in archite
```suggestion
Live cursors are implemented using [Ably Spaces](https://ably.com/docs/products/spaces). The Spaces SDK contains a set of purpose-built APIs that abstract away the complexities involved in managing the state of participants in a collaborative application. It is built on top of Ably's core platform, and so it provides the same performance and scaling guarantees.
```

2024-11-06 17:35 UTC, m-hulbert commented on examples/spaces-live-cursors/page.md
> +* [useCursors()](https://ably.com/docs/spaces/react#useCursors) hook: a hook to track a member's cursor position and provide a view of all members' cursors within a space.
Code styled please.

2024-11-08 13:24 UTC, GregHolmes commented
> The JavaScript example is only displaying cursors when you hover over the text.

Thanks! I've found the issue and resolved it.

2024-11-08 16:57 UTC, m-hulbert approved these changes
That fixed the JS issue 🚀 

Noticed the same minor real-time typo but LGTM other than that

2024-11-08 16:57 UTC, m-hulbert commented on examples/spaces-live-cursors/page.md
> +* [`SpaceProvider`](https://ably.com/docs/spaces/react#spaces-provider): manages the state and functionality of a specific space, providing access to real-time interactions within that space via Reac
Noticed this after the others: real-time --> realtime

2024-11-11 10:49 UTC, merged