[EDU-1655] - Pub/Sub Presence example
ably/docs pull request #2325
Opened 2024-12-03 17:44 UTC by GregHolmes

This PR contains the two code samples for the new Examples section we are creating. It contains a Typescript and a React version for presence with Pub/Sub. Which will be rendered in the code sandbox live examples in the future, along with others.

The README within each directory /examples/pub-sub-presence/javascript and /examples/pub-sub-presence/react contains information on how to get these running.

[Jira epic ticket](https://ably.atlassian.net/browse/EDU-1541)
[Jira ticket](https://ably.atlassian.net/browse/EDU-1655).

2024-12-18 16:33 UTC, NickLittman commented
In the React example, the Presence set isn't hydrating on page load. Any user who joins will only see themselves and anyone who joins after them, not anyone who has joined before them.

The `usePresenceListener` hook exposes the `presenceData` [state object](https://ably.com/docs/getting-started/react#usePresenceListener) which you could use instead of storing the viewer info in your own `viewers` state.

2024-12-18 16:59 UTC, m-hulbert reviewed
2 minor wording suggestions. 

Also still think a manual status would be useful in order to show off `presence.update()` here (and then add that to the page.md)

2024-12-18 16:59 UTC, m-hulbert commented on examples/pub-sub-presence/page.md
> +Presence is implemented using [Ably Pub/Sub](https://ably.com/docs/products/channels). The Ably SDK provides features such as presence, publishing and subscribing to messages within channels in a hig
Suggest we replace the 2nd sentence with the "agreed" upon one for Pub/Sub 🙂

2024-12-18 16:59 UTC, m-hulbert commented on examples/pub-sub-presence/page.md
> +Use presence to display which users are currently online in a channel. Users can also manually update their status, such as to set themselves as 'Away', or write a custom message.
```suggestion
Use presence to display which users are currently 'present' on a channel. Users can also manually update their status, such as to set themselves as 'Away', or write a custom message.
```

2024-12-31 11:11 UTC, GregHolmes commented
> In the React example, the Presence set isn't hydrating on page load. Any user who joins will only see themselves and anyone who joins after them, not anyone who has joined before them.
> 
> The `usePresenceListener` hook exposes the `presenceData` [state object](https://ably.com/docs/getting-started/react#usePresenceListener) which you could use instead of storing the viewer info in your own `viewers` state.

 Good spot. Thank you. I think this was a problem caused by a refactor and I never added it back in.

2025-01-06 23:52 UTC, ttypic requested changes

2025-01-06 23:52 UTC, ttypic commented on examples/pub-sub-presence/javascript/src/script.ts
> +    switch (action) {
I believe we don't recommend this, it can lead to some issues, it's better to refetch presence set here (we are going to provide presence set as one of listener's argument later to make it more useful). Action can be used to show toasters or other notification, not for rebuilding the set (because getting the initial set is not atomic)

2025-01-06 23:52 UTC, ttypic commented on examples/pub-sub-presence/react/src/app/page.tsx
> +    switch (presence.action) {
no need to do this, `presenceData` is always represent actual presence set, so it can be replaced with:

```ts
const { presenceData } = usePresenceListener('viewer-presence')
const viewers: Viewer[] = useMemo(() => presenceData.map(member => ({
      clientId: member.clientId,
      isOnline: true
},  presenceData);

```

2025-01-10 12:59 UTC, ttypic approved these changes
Looks good to me!

2025-01-10 16:08 UTC, m-hulbert approved these changes
Good to go with a rebase 🙂

2025-01-13 16:50 UTC, merged