[EDU-1670] - Pub/Sub history example
ably/docs pull request #2334
Opened 2024-12-11 13:08 UTC by GregHolmes

This PR contains the two code samples for the new Examples section we are creating. It contains a Typescript and a React version for retrieving channel history in pub/sub.

The README within each directory `/examples/pub-sub-history/javascript` and `/examples/pub-sub-history/react` contains information on how to get these running.

[Jira epic ticket](https://ably.atlassian.net/browse/EDU-1541)
[Jira ticket](https://ably.atlassian.net/browse/EDU-1670).

2024-12-18 15:21 UTC, m-hulbert requested changes
I really like this idea / use case. Couple of suggestions: 

* Missing an `.env.sample` in the React folder.
* Need a (You/Me) label for your own client within the list.
* My suggestion would be to not have the step to enter the auction, and you just automatically join rather than having the 2-step process to load/enter. We should be able to publish the messages before someone clicks 'load history' I'd have thought? Then I'd also recommend making the history button within that screen more prominent. At the moment it looks like the bidding button is the more important one. WDYT?

2024-12-18 15:21 UTC, m-hulbert commented on examples/pub-sub-history/page.md
> +Use history to retrieve messages previously published to a channel within an application. Users can retrieve the history for messages such as a bidding history, or status updates.
```suggestion
Use history to retrieve messages that have been previously published to a channel. Users can then start working in your application with context of what happened before they went joined, or came online. Uses include retrieving the values of bids from an auction site before placing your own, or providing the last 2 minutes worth of contextual data in a realtime dashboard.
```

2024-12-18 15:21 UTC, m-hulbert commented on examples/pub-sub-history/page.md
> +History enables users to retrieve historically published messages within an application, allowing them to understand how the current state has been achieved. For example, in an auction site the user
```suggestion
History enables users to retrieve messages that have been previously published within an application. It enables provides users with context as to how the current state has been reached.
```

2024-12-18 15:21 UTC, m-hulbert commented on examples/pub-sub-history/page.md
> +History is implemented using [Ably Pub/Sub](https://ably.com/docs/products/channels). The Ably SDK contains a set of purpose-built APIs that abstract away the complexities involved in architecting Pu
`The Ably SDK contains a set of purpose-built APIs that abstract away the complexities involved in architecting Pub/Sub features.` 

I think this sentence needs replacing for Pub/Sub as it's too abstraction-focussed towards the other products. Maybe something along the lines of:

`The Pub/Sub SDK provides a set of flexible APIs capable of building any realtime application. It is powered by Ably's reliable and scalable platform.` ?

2025-01-06 23:41 UTC, ttypic reviewed
Looks great, add couple of small comments

2025-01-06 23:41 UTC, ttypic commented on examples/pub-sub-history/react/src/app/auction/page.tsx
> +    if (message.name === 'bid') {
I prefer early return it reduce nesting level, that makes code more readable: 


```ts 
if (message.name !== 'bid') return;
...
```

2025-01-06 23:41 UTC, ttypic commented on examples/pub-sub-history/react/src/app/auction/page.tsx
> +        const resultPage = await channel.history();
I believe it's better to wrap only channel code in the try-catch block:

```ts
let messages = [];
try {
   const resultPage = await channel.history();
   messages = resultPage.items;
} catch (error) {
   console.error('Failed to retrieve message history:', error);
   return null;
}
...
```

2025-01-06 23:41 UTC, ttypic commented on examples/pub-sub-history/react/src/app/auction/page.tsx
> +      const resultPage = await channel.history();
same here, with try-catch

2025-01-09 11:07 UTC, merged