Web 4087
ably/docs pull request #2347
Opened 2024-12-17 10:01 UTC by aralovelace

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

A PR description indicating the purpose of the PR.

* [Jira epic ticket](link) - if applicable.
* [Jira ticket](link).

## Review

Instructions on how to review the PR. 

* [Page to review](link)

2024-12-19 22:11 UTC, aralovelace commented
@coderabbitai review

2024-12-19 22:21 UTC, aralovelace commented on src/data/examples.ts
> +        'Enable users to have conversations with each other by sending and receiving messages in a chat room.',
This is not a duplicate, this is from the Dev Ed

2025-01-09 17:31 UTC, jamiehenson commented on src/pages/examples.tsx
> +  const meta_description = 'Examples';
Will do this for now as it's better placeholder content than what's there

2025-01-09 17:33 UTC, jamiehenson commented on src/components/Examples/ExamplesFilter.tsx
> +          />
Will do a more comprehensive overhaul of what's described here

2025-01-09 17:35 UTC, jamiehenson commented on src/components/Examples/ExamplesContent.tsx
> +          </div>
Seems like overkill for this instance. We're not dealing with any external services here or anything of the like.

2025-02-18 14:45 UTC, jamiehenson commented
@coderabbitai review

2025-02-18 17:16 UTC, jamiehenson commented
@aralovelace just a note (since it's your PR so I can't tag you for review) that now the main nav work is in, this has been patched up and is ready for a look ✏️

2025-02-20 11:12 UTC, aralovelace commented on src/components/Layout/Header.tsx
> +      //     contents={[<LeftSidebar inHeader key="nav-mobile-documentation-tab" />, <ExamplesList key="nav-mobile-examples-tab" />]}
Just wondering why this is still commented out. If we merge and push this to production, will it remain commented? Would it be easier to add a feature flag instead?

2025-02-20 14:24 UTC, kennethkalmer commented
I immediately noticed this background and I have to be honest it looks strange to me, and I don't see it in Figma other than being an asset.

![Screenshot 2025-02-20 at 14 18 31](https://github.com/user-attachments/assets/9cb3173d-3ea4-415d-9447-9ddf35e8b82d)

I assume the missing icons are purely because these examples are still being created 😇

2025-02-20 14:35 UTC, kennethkalmer commented on src/components/Layout/Header.tsx
> +      //     contents={[<LeftSidebar inHeader key="nav-mobile-documentation-tab" />, <ExamplesList key="nav-mobile-examples-tab" />]}
@aralovelace we need to land #2383 first _and_ update the website to routes `/examples` to docs

2025-02-20 14:46 UTC, jamiehenson commented on src/components/Layout/Header.tsx
> +      //     contents={[<LeftSidebar inHeader key="nav-mobile-documentation-tab" />, <ExamplesList key="nav-mobile-examples-tab" />]}
We also need to do the sandpack stuff as examples wont be considered complete until then

2025-02-20 14:47 UTC, kennethkalmer requested changes
Looking nice! The background image (grid) (as mentioned in an earlier comment) isn't in the right place, one small copy tweak, and just some feedback on filtering that caught me out.

2025-02-20 14:47 UTC, kennethkalmer commented on src/components/Examples/filter-search-examples.ts
> +        example.products.some((product) => product.toLowerCase().includes(normalizedSearchTerm)) ||
[nitpick] filtering on product has a strange effect when you search for "live" as it matches every single example and I came here to report what I thought was a bug:

https://github.com/user-attachments/assets/dda8f788-fa88-44a6-b2cd-22646813237a

2025-02-20 14:47 UTC, kennethkalmer commented on src/components/Examples/ExamplesNoResults.tsx
> +          Suggest an example
Lower case `S`, it reads strange:

![image](https://github.com/user-attachments/assets/e8f8a059-b935-45ff-9f87-20af6e037045)

2025-02-20 14:58 UTC, jamiehenson commented on src/components/Examples/filter-search-examples.ts
> +        example.products.some((product) => product.toLowerCase().includes(normalizedSearchTerm)) ||
This is because all of the placeholder examples happen to be tagged with a use case of "live chat". Perhaps a UX problem, but this will be less obvious when there is a greater diversity of examples

2025-02-20 15:20 UTC, jamiehenson commented
@kennethkalmer the dodgy background was down to a gatsby image wrapper class that overrode the absolute positioning classes - [it's as expected](https://ably-docs-web-4087-jekp85jqo8n.herokuapp.com/docs/examples) now

After a tick here, I'll add `navigate('/', { replace: true })` to the examples page to redirect away from it, unless you can think of a more Gatsby way to nullify a pages route that I didn't get from the first look at the docs

2025-02-20 15:28 UTC, kennethkalmer commented on src/components/Examples/filter-search-examples.ts
> +        example.products.some((product) => product.toLowerCase().includes(normalizedSearchTerm)) ||
thought so, I just wanted to bring it to our attention before it becomes "that is how it always was" 🤣

2025-02-20 15:32 UTC, kennethkalmer commented
> After a tick here, I'll add `navigate('/', { replace: true })` to the examples page to redirect away from it, unless you can think of a more Gatsby way to nullify a pages route that I didn't get from the first look at the docs

@jamiehenson sounds reasonable to me!

2025-02-20 15:33 UTC, kennethkalmer approved these changes
:shipit:

2025-02-20 15:55 UTC, aralovelace commented on src/components/Layout/Header.tsx
> +      //     contents={[<LeftSidebar inHeader key="nav-mobile-documentation-tab" />, <ExamplesList key="nav-mobile-examples-tab" />]}
okay noted @jamiehenson  @kennethkalmer  I cant approved it but all good for me

2025-02-20 16:06 UTC, merged