[EDU-1556] Split channels content into more consumable sections
ably/docs pull request #2349
Opened 2024-12-17 18:53 UTC by m-hulbert

> _NOTE TO REVIEWERS_ - please **do not review PRs in the `DRAFT` state**, as the PR may change substantially before it is ready to review. Thanks.

## Description

This PR splits up the existing `/channels/` page into more manageable sections:

* A publish-subscribe section
** The basics of using pub-sub
** Advanced pub-sub usage
* A channels section
** Channel concepts
** Channel states
** Existing channel options
* A messages section
** Message concepts
** Message batching

This PR also removes message interactions content. 

Still to-do once this is broadly agreed:
* Update all links to the new sections.
* Prioritise other message content (conflation and extras)

2025-01-22 14:01 UTC, kavalerov requested changes
I like the overall separation. Left a few comments on the content in specific areas.

2025-01-22 16:00 UTC, m-hulbert commented on content/channels/index.textile
> +h2(#get). Get a channel
Yes, this is actually a good shout I have updated it.

2025-01-22 16:00 UTC, m-hulbert commented on content/channels/index.textile
> +<p>Although Ably recommends that you use channels to distribute work more evenly across the cluster, there is an associated cost for a high number of channels.</p>
Updated.

2025-01-22 16:00 UTC, m-hulbert commented on content/channels/index.textile
> +<p>Namespaces are not required to refer to a set of channels within a capability. A resource specifier, such as @foo:*@, a glob expression, will match a channel named @foo:bar@, even without a @foo@
Reworded slightly.

2025-01-22 16:02 UTC, m-hulbert commented on content/channels/states.textile
> +Normally, errors in attaching to a channel are communicated through the "@attach()@":/api/realtime-sdk/channels#attach callback. For implicit attaches, where a client only calls @subscribe()@, there
Yes, good point I have updated this.

2025-01-22 16:02 UTC, m-hulbert commented on content/channels/states.textile
> +* The first time a client attaches to a channel on a fresh connection, @resumed@ will be @false@, as there was nothing to continue from.
Yes, I need to make a few diagrams and this is on the list.

2025-01-23 09:12 UTC, kavalerov approved these changes

2025-01-23 10:40 UTC, franrob-projects approved these changes
I like the logic behind this. All the links are good 👍

2025-01-23 12:01 UTC, merged