Revert "[WEB-381] Add GA tracking to docs.ably.io"
ably/docs pull request #938
Opened 2020-08-11 14:05 UTC by MarkWoulfeAbly

Reverts ably/docs#905

Closes #931 

docs.ably.io should have its own GA property, this will be addressed in a separate PR if necessary.

2020-08-28 11:16 UTC, mattheworiordan commented
I do not understand why you are proposing to create a separate PR to add docs.ably.io tracking instead of just switching out `GTM-TZ37KKW` now with a new GA code? That would require less work (fewer reviews, one small change) and give you visibility into the dosc site usage at the same time.

2020-08-28 11:17 UTC, mattheworiordan requested changes
I would prefer to see this fixed (i.e. new tracking code) as opposed to remove tracking completely.

2020-08-28 13:53 UTC, MarkWoulfeAbly commented
I had mentioned that possibility to @DominikElmiger but at the time of creating the PR he suggested simply removing it would be faster. Dom, do you have the availability to create a new code to replace the old one instead?

2021-02-10 17:11 UTC, tbedford commented
I've created DOC-259 and I will create a new PR to tackle this.

2021-02-10 17:11 UTC, closed without merging